AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 bucket for LINE AWS Usage Tracker"

Resources:
  UsageTrackerBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-usage-tracker-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldReports
            Status: Enabled
            ExpirationInDays: 365
            Prefix: cur-reports/
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  UsageTrackerBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref UsageTrackerBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: EnforceSSLOnly
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "arn:aws:s3:::${UsageTrackerBucket}"
              - !Sub "arn:aws:s3:::${UsageTrackerBucket}/*"
            Condition:
              Bool:
                aws:SecureTransport: false

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref UsageTrackerBucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"
